# Site settings
title:              Daniel Augustin
email:              danielaugustin300@gmail.com
description:        "Portfolio template for students in the MSR program at Northwestern University"
url:                "http://localhost:4000"
baseurl:            /msr-student-template


# Build settings
markdown:           kramdown
permalink:          pretty

# Collection definitions and settings
collections:
  projects:
    output: true
    permalink: /projects/:path/
